
package Vistas;

import AccesoDatos.IngredienteData;
import Entidades.Ingrediente;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class V_Table_Ingredientes extends javax.swing.JInternalFrame {

    private static int indiceIngrediente;
    
    private String tbiIdIngrediente = "";
    private String tbiNombre = "";
    private String tbiCalorias = "";
    
    DefaultTableModel modeloIngre;
    
    boolean contieneNumero = false;
    
    TableRowSorter<TableModel> TRSI;
    
    public V_Table_Ingredientes() {
        initComponents();
        
        modeloIngre = (DefaultTableModel) jTableIngredientes.getModel();
        TRSI = new TableRowSorter<>(modeloIngre);
        jTableIngredientes.setRowSorter(TRSI);
        
        cargaTablaIngredientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableIngredientes = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextBuscarIngrediente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBtnAgregar = new javax.swing.JButton();
        jBtnModificar = new javax.swing.JButton();
        jBtnCargarTabla = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setTitle("Administración de Ingredientes");

        jTableIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Calorias [x100gs]"
            }
        ));
        jTableIngredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableIngredientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableIngredientes);
        if (jTableIngredientes.getColumnModel().getColumnCount() > 0) {
            jTableIngredientes.getColumnModel().getColumn(0).setPreferredWidth(25);
            jTableIngredientes.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTableIngredientes.getColumnModel().getColumn(2).setPreferredWidth(25);
        }

        jLabel5.setText("Buscar por Nombre:");

        jTextBuscarIngrediente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextBuscarIngredienteKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Tabla Ingredientes");

        jBtnAgregar.setText("Agregar");
        jBtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAgregarMouseClicked(evt);
            }
        });
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });

        jBtnModificar.setText("Modificar");
        jBtnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnModificarMouseClicked(evt);
            }
        });
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });

        jBtnCargarTabla.setText("Refresca");
        jBtnCargarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCargarTablaActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jBtnAgregar)
                            .addGap(18, 18, 18)
                            .addComponent(jBtnModificar)
                            .addGap(31, 31, 31)
                            .addComponent(jBtnCargarTabla)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextBuscarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextBuscarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAgregar)
                    .addComponent(jBtnModificar)
                    .addComponent(jBtnCargarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtnAgregar, jBtnCargarTabla, jBtnModificar, jButton1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        V_Form_Ingrediente vmi = new V_Form_Ingrediente();
        vmi.setVisible(true);
        vmi.pack();
        vmi.setLocationRelativeTo(null);
        vmi.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        vmi.setAccion("Agregar");
        vmi.setTitle("Agregando un nuevo ingrediente...");
    }

    
    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {
        
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jBtnCargarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCargarTablaActionPerformed
        cargaTablaIngredientes();
    }//GEN-LAST:event_jBtnCargarTablaActionPerformed

    private void jTableIngredientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableIngredientesMouseClicked
        indiceIngrediente = jTableIngredientes.getSelectedRow();

        tbiIdIngrediente = modeloIngre.getValueAt(indiceIngrediente,0).toString();
        tbiNombre  = modeloIngre.getValueAt(indiceIngrediente,1).toString();
        tbiCalorias = modeloIngre.getValueAt(indiceIngrediente,2).toString();
    }//GEN-LAST:event_jTableIngredientesMouseClicked

    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed
        if (tbiIdIngrediente != "") {

            V_Form_Ingrediente vmi = new V_Form_Ingrediente();
            vmi.setVisible(true);
            vmi.pack();
            vmi.setLocationRelativeTo(null);
            vmi.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            vmi.setjTidIngrediente(tbiIdIngrediente);
            vmi.setjTnombre(tbiNombre);
            vmi.setjTcalorias(tbiCalorias);

            vmi.setAccion("Modificar");
            String titulo = "Modificando el ingrediente: " + tbiNombre;
            vmi.setTitle(titulo);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un ingrediente ", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnModificarActionPerformed

    private void jTextBuscarIngredienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBuscarIngredienteKeyReleased
        IngredienteData ingreData = new IngredienteData();
        if (modeloIngre.getRowCount()>0) {
          borrarIngredientes();    
        }
        
        if (!jTextBuscarIngrediente.getText().isEmpty()) {
            for (Ingrediente ingre : ingreData.litarIngredientes()) {
                if (ingre.getNombre().startsWith(jTextBuscarIngrediente.getText())) {
                    modeloIngre.addRow(new Object[]{ingre.getIdIngrediente(),ingre.getNombre(),
                    ingre.getCaloriasPor100GR()});
                }
            }
        } else {
        }
    }//GEN-LAST:event_jTextBuscarIngredienteKeyReleased

    private void jBtnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnModificarMouseClicked

    }//GEN-LAST:event_jBtnModificarMouseClicked

    private void jBtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarMouseClicked

    }//GEN-LAST:event_jBtnAgregarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnCargarTabla;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTableIngredientes;
    private javax.swing.JTextField jTextBuscarIngrediente;
    // End of variables declaration//GEN-END:variables

    
    
    

    //INGREDIENTES
    public static void modificaFilaIngredientes(Object[] dataFila){
        DefaultTableModel model = (DefaultTableModel) jTableIngredientes.getModel();
        //model.setValueAt((Integer.parseInt((String) dataFila[0])), indiceIngrediente, 0); 
        model.setValueAt(((String) dataFila[1]), indiceIngrediente, 1); 
        model.setValueAt((Integer.parseInt((String) dataFila[2])), indiceIngrediente, 2); 

        // Notifica a la tabla que la fila ha sido modificada
        model.fireTableRowsUpdated(indiceIngrediente, indiceIngrediente);
        
        
    }
    
    public static void agregaFilaIngredientes(Object[] dataFila){
        DefaultTableModel model = (DefaultTableModel) jTableIngredientes.getModel();
        model.addRow(dataFila);
    }
    
    public void cargaTablaIngredientes() {
        DefaultTableModel datos = (DefaultTableModel) jTableIngredientes.getModel();
        datos.setNumRows(0);
        IngredienteData id = new IngredienteData();
        id.litarIngredientes().forEach((Ingrediente i) -> {
            Object[] fila = new Object[3];
            fila[0] = i.getIdIngrediente();
            fila[1] = i.getNombre();
            fila[2] = i.getCaloriasPor100GR();
            datos.addRow(fila);
        });
        jTextBuscarIngrediente.setText("");
    }
    
    private void borrarIngredientes() {
        int f = modeloIngre.getRowCount() - 1;
        for (; f >= 0; f--) {
            modeloIngre.removeRow(f);
        }
    }

    private void borrarFilas() {
        for (int f = jTableIngredientes.getRowCount() - 1; f >= 0; f--) {
            modeloIngre.removeRow(f);
        }
    }
    
        

    
    void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
