
package Vistas;

import Entidades.Comida;
import AccesoDatos.ComidaData;
import AccesoDatos.IngredienteComidaData;
import AccesoDatos.IngredienteData;
import Entidades.Ingrediente;
import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class V_Table_AdminComidas extends javax.swing.JInternalFrame {

    //V_Form_ModificarComida vmc = new V_Form_ModificarComida();
    boolean contieneNumero = false;
    
    private static int indiceComida;
    private static int indiceIngrediente;
    private static int indiceIngreComi;
    
    private String tbcIdComida = "";
    private String tbcNombre = "";
    private String tbcDetalle = "";
    private String tbcCalorias = "";
    
    private String tbiIdIngrediente = "";
    private String tbiNombre = "";
    private String tbiCalorias = "";
    
    private String tbicIdingredienteComida = "";
    
    DefaultTableModel modeloComida;
    DefaultTableModel modeloIngre;
    DefaultTableModel modeloIngreComi;

    TableRowSorter<TableModel> TRS;
    TableRowSorter<TableModel> TRSI;
    TableRowSorter<TableModel> TRSIC;
    
    public V_Table_AdminComidas() {
        initComponents();
        
        modeloComida = (DefaultTableModel) jTableComidas.getModel();
        TRS = new TableRowSorter<>(modeloComida);
        jTableComidas.setRowSorter(TRS);
        
        modeloIngre = (DefaultTableModel) jTableIngredientes.getModel();
        TRSI = new TableRowSorter<>(modeloIngre);
        jTableIngredientes.setRowSorter(TRSI);
        
        modeloIngreComi = (DefaultTableModel) jTableIngreComi.getModel();
        TRSIC = new TableRowSorter<>(modeloIngreComi);
        jTableIngreComi.setRowSorter(TRSIC);
        
        refresca();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPbuscarComida = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableIngredientes = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextBuscarIngrediente = new javax.swing.JTextField();
        jBtnAgregaComidaIngrediente = new javax.swing.JButton();
        jBtnRefresca = new javax.swing.JButton();
        jPcomidas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableComidas = new javax.swing.JTable();
        jTbuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBtnAgregarComida = new javax.swing.JButton();
        jBtnModificar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableIngreComi = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jBtnEliminar = new javax.swing.JButton();
        jTtotalCalorias = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Administración de comidas");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Tabla de Ingredientes");

        jTableIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idIngrediente", "Nombre", "Calorias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableIngredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableIngredientesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableIngredientes);
        if (jTableIngredientes.getColumnModel().getColumnCount() > 0) {
            jTableIngredientes.getColumnModel().getColumn(0).setPreferredWidth(25);
            jTableIngredientes.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTableIngredientes.getColumnModel().getColumn(2).setPreferredWidth(30);
        }

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Buscar por Nombre");

        jTextBuscarIngrediente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextBuscarIngredienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextBuscarIngredienteKeyTyped(evt);
            }
        });

        jBtnAgregaComidaIngrediente.setText("Agregar ingrediente a Comida");
        jBtnAgregaComidaIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregaComidaIngredienteActionPerformed(evt);
            }
        });

        jBtnRefresca.setText("Refresca");
        jBtnRefresca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRefrescaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPbuscarComidaLayout = new javax.swing.GroupLayout(jPbuscarComida);
        jPbuscarComida.setLayout(jPbuscarComidaLayout);
        jPbuscarComidaLayout.setHorizontalGroup(
            jPbuscarComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbuscarComidaLayout.createSequentialGroup()
                .addGroup(jPbuscarComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPbuscarComidaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(jPbuscarComidaLayout.createSequentialGroup()
                        .addGroup(jPbuscarComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPbuscarComidaLayout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jBtnAgregaComidaIngrediente))
                            .addGroup(jPbuscarComidaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPbuscarComidaLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextBuscarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jBtnRefresca)))
                .addContainerGap())
        );
        jPbuscarComidaLayout.setVerticalGroup(
            jPbuscarComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbuscarComidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPbuscarComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextBuscarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnRefresca, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnAgregaComidaIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTableComidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Detalle", "Calorias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableComidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableComidasMouseClicked(evt);
            }
        });
        jTableComidas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableComidasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableComidas);
        if (jTableComidas.getColumnModel().getColumnCount() > 0) {
            jTableComidas.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTableComidas.getColumnModel().getColumn(1).setPreferredWidth(70);
            jTableComidas.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTableComidas.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        jTbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTbuscarKeyReleased(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Buscar por Nombre");

        jBtnAgregarComida.setText("Agregar");
        jBtnAgregarComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarComidaActionPerformed(evt);
            }
        });

        jBtnModificar.setText("Modificar");
        jBtnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnModificarMouseClicked(evt);
            }
        });
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Tabla Comidas");

        jTableIngreComi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "idComida", "IdIngrediente", "Nombre", "Calorias [x100gr]"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableIngreComi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableIngreComiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableIngreComi);
        if (jTableIngreComi.getColumnModel().getColumnCount() > 0) {
            jTableIngreComi.getColumnModel().getColumn(0).setResizable(false);
            jTableIngreComi.getColumnModel().getColumn(0).setPreferredWidth(25);
            jTableIngreComi.getColumnModel().getColumn(1).setResizable(false);
            jTableIngreComi.getColumnModel().getColumn(1).setPreferredWidth(25);
            jTableIngreComi.getColumnModel().getColumn(2).setResizable(false);
            jTableIngreComi.getColumnModel().getColumn(2).setPreferredWidth(25);
            jTableIngreComi.getColumnModel().getColumn(3).setPreferredWidth(70);
            jTableIngreComi.getColumnModel().getColumn(4).setPreferredWidth(45);
        }

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Tabla Comida-Ingredientes");

        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        jTtotalCalorias.setEditable(false);
        jTtotalCalorias.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPcomidasLayout = new javax.swing.GroupLayout(jPcomidas);
        jPcomidas.setLayout(jPcomidasLayout);
        jPcomidasLayout.setHorizontalGroup(
            jPcomidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcomidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPcomidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPcomidasLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPcomidasLayout.createSequentialGroup()
                        .addGroup(jPcomidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPcomidasLayout.createSequentialGroup()
                                .addComponent(jBtnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTtotalCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPcomidasLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPcomidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPcomidasLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(jTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPcomidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel9)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPcomidasLayout.createSequentialGroup()
                                            .addComponent(jBtnAgregarComida)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jBtnModificar)))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(93, 93, 93))))
        );
        jPcomidasLayout.setVerticalGroup(
            jPcomidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcomidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPcomidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPcomidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAgregarComida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPcomidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTtotalCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPbuscarComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPcomidas, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPcomidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPbuscarComida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableComidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableComidasMouseClicked
        indiceComida = jTableComidas.getSelectedRow();
        tbcIdComida = modeloComida.getValueAt(indiceComida,0).toString();
        tbcNombre = modeloComida.getValueAt(indiceComida,1).toString();
        tbcDetalle = modeloComida.getValueAt(indiceComida,2).toString();
        tbcCalorias = modeloComida.getValueAt(indiceComida,3).toString();

        //buscaComida(idComida);
        int idComida = Integer.parseInt(tbcIdComida);
        cargaTablaIngreComi(idComida);

    }//GEN-LAST:event_jTableComidasMouseClicked

    private void jTableComidasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableComidasKeyPressed
        
        
    }//GEN-LAST:event_jTableComidasKeyPressed

    private void jTbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbuscarKeyReleased
        ComidaData comiData = new ComidaData();
        borrarFilas();
        if (!jTbuscar.getText().isEmpty()) {
            //for (Comida comi : ComidaData.listarComidas()) {
            for (Comida comi : comiData.listarComidas() ) {
                if (comi.getNombre().startsWith(jTbuscar.getText())) {
                    modeloComida.addRow(new Object[]{comi.getIdComida(),comi.getNombre(), comi.getDetalle(),
                        comi.getCantCalorias()});
                }
            }
        } 
    }//GEN-LAST:event_jTbuscarKeyReleased

    private void jBtnAgregarComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarComidaActionPerformed
        V_Form_Comida vmc = new V_Form_Comida();
        vmc.setVisible(true);
        vmc.pack();
        vmc.setLocationRelativeTo(null);
        vmc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        vmc.setAccion("Agregar");
        vmc.setTitle("Agregando una Comida...");
    }//GEN-LAST:event_jBtnAgregarComidaActionPerformed

    private void jBtnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnModificarMouseClicked
    }//GEN-LAST:event_jBtnModificarMouseClicked

    
    
    private void jTableIngredientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableIngredientesMouseClicked
        indiceIngrediente = jTableIngredientes.getSelectedRow();

        tbiIdIngrediente = modeloIngre.getValueAt(indiceIngrediente,0).toString();
        tbiNombre  = modeloIngre.getValueAt(indiceIngrediente,1).toString();
        tbiCalorias = modeloIngre.getValueAt(indiceIngrediente,2).toString();

    }//GEN-LAST:event_jTableIngredientesMouseClicked

    private void jTextBuscarIngredienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBuscarIngredienteKeyReleased
        IngredienteData ingreData = new IngredienteData();
        if (modeloIngre.getRowCount()>0) {
          borrarIngredientes();    
        }
        
        if (!jTextBuscarIngrediente.getText().isEmpty()) {
            for (Ingrediente ingre : ingreData.litarIngredientes()) {
                if (ingre.getNombre().startsWith(jTextBuscarIngrediente.getText())) {
                    modeloIngre.addRow(new Object[]{ingre.getIdIngrediente(),ingre.getNombre(),
                    ingre.getCaloriasPor100GR()});
                }
            }
        } else {
        }
    }//GEN-LAST:event_jTextBuscarIngredienteKeyReleased

    private void jBtnAgregaComidaIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregaComidaIngredienteActionPerformed
        insertComidaIngrediente();
    }//GEN-LAST:event_jBtnAgregaComidaIngredienteActionPerformed

    private void jTextBuscarIngredienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBuscarIngredienteKeyTyped
        IngredienteData ingreData = new IngredienteData();
        if (modeloIngre.getRowCount()>0) {
          borrarIngredientes();    
        }
        
        if (!jTextBuscarIngrediente.getText().isEmpty()) {
            for (Ingrediente ingre : ingreData.litarIngredientes()) {
                if (ingre.getNombre().startsWith(jTextBuscarIngrediente.getText())) {
                    modeloIngre.addRow(new Object[]{ingre.getIdIngrediente(),ingre.getNombre(),
                    ingre.getCaloriasPor100GR()});
                }
            }
        } else {
        }    
    }//GEN-LAST:event_jTextBuscarIngredienteKeyTyped

    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed
        if (tbcIdComida!="") {

            V_Form_Comida vmc = new V_Form_Comida();
            vmc.setVisible(true);
            vmc.pack();
            vmc.setLocationRelativeTo(null);
            vmc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            vmc.setjTidComida(tbcIdComida);
            vmc.setjTnombre(tbcNombre);
            vmc.setjTdetalle(tbcDetalle);
            vmc.setjTcalorias(tbcCalorias);

            vmc.setAccion("Modificar");
            String titulo = "Modificando comida: " + tbcNombre;
            vmc.setTitle(titulo);

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una comida ", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnModificarActionPerformed

    private void jTableIngreComiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableIngreComiMouseClicked
        indiceIngreComi = jTableIngreComi.getSelectedRow();
        tbicIdingredienteComida = modeloIngreComi.getValueAt(indiceIngreComi,0).toString();
        
    }//GEN-LAST:event_jTableIngreComiMouseClicked

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        eliminaIngreComi();
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBtnRefrescaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRefrescaActionPerformed
        refresca();
    }//GEN-LAST:event_jBtnRefrescaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregaComidaIngrediente;
    private javax.swing.JButton jBtnAgregarComida;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jBtnRefresca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPbuscarComida;
    private javax.swing.JPanel jPcomidas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JTable jTableComidas;
    private static javax.swing.JTable jTableIngreComi;
    private javax.swing.JTable jTableIngredientes;
    private javax.swing.JTextField jTbuscar;
    private javax.swing.JTextField jTextBuscarIngrediente;
    private javax.swing.JTextField jTtotalCalorias;
    // End of variables declaration//GEN-END:variables

    //Comida-Ingredientes
    public void insertComidaIngrediente() {
        if (!validaDatos()) {
            int idComida = Integer.parseInt(tbcIdComida);
            int idIngrediente =  Integer.parseInt(tbiIdIngrediente);
            IngredienteComidaData ingreComiData = new IngredienteComidaData();        
            ingreComiData.insertIngredienteComida(idComida, idIngrediente);
            cargaTablaIngreComi(idComida);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una comida y un ingrediente", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void cargaTablaIngreComi(int idComida) {
        
        DefaultTableModel ingreComiDatos = (DefaultTableModel) jTableIngreComi.getModel();
        ingreComiDatos.setNumRows(0);
        IngredienteComidaData icd = new IngredienteComidaData();
        ArrayList<Object[]> datos = icd.selectIngredienteComida(idComida);
        for (Object[] fila : datos) {
            ingreComiDatos.addRow(fila);
        }
        
        System.out.println("Filas: " + modeloIngreComi.getRowCount());
        
        sumaCalorias();
    }
 
    public void sumaCalorias(){
        int totalCalorias = 0;
        int calorias = 0;
        for (int fila = 0; fila < modeloIngreComi.getRowCount(); fila++) {
            calorias = Integer.parseInt(modeloIngreComi.getValueAt(fila, 4).toString());
            totalCalorias += calorias;
        }    
        jTtotalCalorias.setText(String.valueOf(totalCalorias));
        actualizaCalorias(totalCalorias);
    }
    
    
    
    public void eliminaIngreComi() {
        if (tbicIdingredienteComida != "") {

            modeloIngreComi.removeRow(indiceIngreComi);
            jTableIngreComi.repaint();

            //Elimina registro de la base de datos
            IngredienteComidaData ingreComi = new IngredienteComidaData();
            System.out.println("id: " + Integer.parseInt(tbicIdingredienteComida));
            ingreComi.deleteIngredienteComida(Integer.parseInt(tbicIdingredienteComida));
            sumaCalorias();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione el ingrediente a eliminar", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void borrarFilasIngreComi() {
        int f = jTableIngreComi.getRowCount() - 1;
        for (; f >= 0; f--) {
            modeloIngreComi.removeRow(f);
        }
    }
    
    //Ingredientes
    public void cargaTablaIngredientes() {
        DefaultTableModel datos = (DefaultTableModel) jTableIngredientes.getModel();
        
        datos.setNumRows(0);
        IngredienteData id = new IngredienteData();
        for (Ingrediente i : id.litarIngredientes()) {
            Object[] fila = new Object[3];
            fila[0] = i.getIdIngrediente();
            fila[1] = i.getNombre();
            fila[2] = i.getCaloriasPor100GR();
            datos.addRow(fila);
        }
    }

    private void borrarIngredientes() {
        int f = modeloIngre.getRowCount() - 1;
        for (; f >= 0; f--) {
            modeloIngre.removeRow(f);
        }
    }
    
    //Comidas
    public static void agregarFilaTablaComidas(Object datosFila){
        DefaultTableModel model = (DefaultTableModel) jTableComidas.getModel();
        model.addRow((Object[]) datosFila);
    }
    
    public static void agregaFilaComidas(Object[] dataFila){
        DefaultTableModel model = (DefaultTableModel) jTableComidas.getModel();
        model.addRow(dataFila);
    }
    
    public void actualizaCalorias(int calorias) {
            //Modifica registro en base de datos
            Comida comi = new Comida(Integer.valueOf(tbcIdComida),
                    tbcNombre, tbcDetalle, calorias);
            ComidaData comiData = new ComidaData();
            comiData.modificarComida(comi);

            //Modifica calorias en Tabla Comida de V_Table_AdminComidas
            DefaultTableModel model = (DefaultTableModel) jTableComidas.getModel();
            model.setValueAt((calorias), indiceComida, 3);
            model.fireTableRowsUpdated(indiceComida, indiceComida);
    }
        
    public static void modificaFilaComidas(Object[] dataFila){
        DefaultTableModel model = (DefaultTableModel) jTableComidas.getModel();
        //model.setValueAt((Integer.parseInt((String) dataFila[0])), indiceComida, 0); 
        model.setValueAt(((String) dataFila[1]), indiceComida, 1); 
        model.setValueAt(((String) dataFila[2]), indiceComida, 2); 
        model.setValueAt((Integer.parseInt((String) dataFila[3])), indiceComida, 3); 
        model.fireTableRowsUpdated(indiceComida, indiceComida);
    }

    public void cargaTablaComida() {
        DefaultTableModel datos = (DefaultTableModel) jTableComidas.getModel();
        datos.setNumRows(0);
        ComidaData cd = new ComidaData();
        cd.listarComidas().forEach((c) -> {
            Object[] fila = new Object[4];
            fila[0] = c.getIdComida();
            fila[1] = c.getNombre();
            fila[2] = c.getDetalle();
            fila[3] = c.getCantCalorias();
            datos.addRow(fila);
        });
    }
    
    private void borrarFilas() {
        int f = jTableComidas.getRowCount() - 1;
        for (; f >= 0; f--) {
            modeloComida.removeRow(f);
        }
    }    
    
    
    //Validaciones
    public void validaNumero(java.awt.event.KeyEvent evt) {
        final char tecla = evt.getKeyChar();
        if (Character.isDigit(tecla)
                || tecla == KeyEvent.VK_BACKSPACE
                || tecla == KeyEvent.VK_DELETE
                || (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V)) {
        } else {
            evt.consume();
        }
    }
    
    public boolean validaDatos() {
        if (tbcIdComida.isEmpty() || tbiIdIngrediente.isEmpty()
                || tbiNombre.isEmpty() || tbiCalorias.isEmpty()) {
            return true;
        } else {
            return false;
        }
    }
    
     public void refresca(){
        jTextBuscarIngrediente.setText("");
        jTbuscar.setText("");
        cargaTablaIngredientes();
        cargaTablaComida();
        borrarFilasIngreComi();
    }
}
